//! Phase 9.0 (PURA-284 / 9.0-rbac) — fine-grained moderation permission
//! catalog and effective-permission resolution.
//!
//! Plan §6 (board decision 5): the three coarse roles (`admin` / `moderator`
//! / `viewer`) stay as the page-level gate; on top, 9.0 adds an action-level
//! `moderation.*` permission catalog checked by the `RequirePermission`
//! extractor (`crate::auth::extractors`).
//!
//! Resolution — [`effective_permissions`] / [`has_permission`]:
//!  - `admin`     → implicitly holds the entire catalog (decision 5:
//!    "`admin` implicitly holds all").
//!  - `moderator` → role-default set ∪ explicit `user_permission` grants.
//!  - `viewer`    → explicit `user_permission` grants only — a viewer holds
//!    nothing by default (plan §6: "a `viewer` sees nothing
//!    moderation").
//!
//! Security posture (secure-by-default, least privilege): the `moderator`
//! default set deliberately **excludes** `moderation.action.ban_ip`. An IP
//! ban carries collateral damage — CGNAT and shared addresses mean one ban
//! can lock out unrelated users — so the plan calls it out as "a separate
//! collateral-damage gate". It is therefore never granted by role; holding
//! it requires an explicit per-user `user_permission` grant.
//!
//! Lens: AuthZ (least privilege, fail-closed), Input handling (the grant
//! API rejects any string outside [`MODERATION_PERMISSIONS`] so an unknown
//! permission can never be persisted).

use std::collections::BTreeSet;

/// A compile-time moderation permission marker. Implemented by the
/// zero-sized structs generated by [`moderation_catalog!`]; the
/// `RequirePermission<P>` extractor is generic over this trait so a
/// permission can never be mistyped or invented at a call site — the gate
/// is only ever parameterised with a catalog member.
pub trait ModPermission {
    /// The wire/storage permission string this marker gates.
    const PERMISSION: &'static str;
}

/// Generates the catalog: one zero-sized marker struct + [`ModPermission`]
/// impl per permission, plus the flat [`MODERATION_PERMISSIONS`] slice. A
/// single source of truth keeps the markers and the runtime catalog from
/// drifting apart.
macro_rules! moderation_catalog {
    ( $( $(#[$m:meta])* $ident:ident => $perm:literal ),+ $(,)? ) => {
        $(
            $(#[$m])*
            #[derive(Debug, Clone, Copy)]
            pub struct $ident;

            impl ModPermission for $ident {
                const PERMISSION: &'static str = $perm;
            }
        )+

        /// Every permission string in the `moderation.*` catalog (plan §6).
        /// The grant API validates against this slice; nothing else can be
        /// written into `user_permission`.
        pub const MODERATION_PERMISSIONS: &[&str] = &[ $( $perm ),+ ];
    };
}

moderation_catalog! {
    /// See the TS6 complaint queue.
    ComplaintView    => "moderation.complaint.view",
    /// Dismiss / action a complaint.
    ComplaintResolve => "moderation.complaint.resolve",
    /// Read cases and their action timelines.
    CaseView         => "moderation.case.view",
    /// Open / resolve / reopen cases.
    CaseManage       => "moderation.case.manage",
    /// Kick a client.
    ActionKick       => "moderation.action.kick",
    /// Server / channel mute and unmute.
    ActionMute       => "moderation.action.mute",
    /// UID / myTeamSpeak-ident ban.
    ActionBan        => "moderation.action.ban",
    /// IP ban — separate collateral-damage gate (plan §6); never granted by
    /// role, requires an explicit per-user grant.
    ActionBanIp      => "moderation.action.ban_ip",
    /// Read moderator notes on a user.
    NoteView         => "moderation.note.view",
    /// Write moderator notes on a user.
    NoteWrite        => "moderation.note.write",
    /// Per-user moderation history pane.
    HistoryView      => "moderation.history.view",
}

/// Permissions seeded for the `moderator` role (plan §6: "a default set is
/// seeded for `moderator` so the role still means something out of the
/// box").
///
/// This is the **entire catalog except `moderation.action.ban_ip`**. The IP
/// ban is a collateral-damage gate and is never role-granted; see the module
/// docs. The `moderation_default_is_catalog_minus_ban_ip` test pins this
/// invariant so a future catalog addition cannot silently widen the role.
pub const MODERATOR_DEFAULT_PERMISSIONS: &[&str] = &[
    "moderation.complaint.view",
    "moderation.complaint.resolve",
    "moderation.case.view",
    "moderation.case.manage",
    "moderation.action.kick",
    "moderation.action.mute",
    "moderation.action.ban",
    "moderation.note.view",
    "moderation.note.write",
    "moderation.history.view",
];

/// True if `permission` is a member of the `moderation.*` catalog.
///
/// The grant API (`PUT /api/users/{id}/permissions`) rejects anything that
/// is not — an unknown or stale permission string can never be persisted
/// into `user_permission` (fail-closed input handling).
pub fn is_known_permission(permission: &str) -> bool {
    MODERATION_PERMISSIONS.contains(&permission)
}

/// The implicit permission set a role carries *before* explicit grants.
///
/// `admin` is intentionally not handled here — it short-circuits to the full
/// catalog inside [`effective_permissions`] / [`has_permission`]. This
/// returns the moderator default for `moderator` and an empty slice for
/// every other role (`viewer`, or any unknown role — fail-closed).
pub fn role_default_permissions(role: &str) -> &'static [&'static str] {
    match role {
        "moderator" => MODERATOR_DEFAULT_PERMISSIONS,
        _ => &[],
    }
}

/// Resolve the effective permission set for a user.
///
/// - `admin` → the entire catalog (decision 5: "`admin` implicitly holds
///   all"). Explicit grants are irrelevant.
/// - any other role → `role_default_permissions(role)` ∪ `explicit_grants`,
///   intersected with the known catalog so a stale `user_permission` row for
///   a since-removed permission can never widen access.
///
/// Returns a sorted [`BTreeSet`] so the `GET /api/users/{id}/permissions`
/// response is deterministic.
pub fn effective_permissions<I, S>(role: &str, explicit_grants: I) -> BTreeSet<String>
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    if role == "admin" {
        return MODERATION_PERMISSIONS
            .iter()
            .map(|p| (*p).to_string())
            .collect();
    }

    let mut set: BTreeSet<String> = role_default_permissions(role)
        .iter()
        .map(|p| (*p).to_string())
        .collect();
    for grant in explicit_grants {
        let grant = grant.as_ref();
        if is_known_permission(grant) {
            set.insert(grant.to_string());
        }
    }
    set
}

/// Authorization check used by the `RequirePermission` extractor: does a
/// user with `role` and `explicit_grants` hold `wanted`?
///
/// Fail-closed in every ambiguous case:
/// - `admin` holds everything **in the catalog** — an unknown `wanted`
///   string is still denied, so a typo at a dynamic call site cannot pass.
/// - a non-catalog `wanted` is always denied.
/// - any role other than `admin`/`moderator` falls through to "explicit
///   grants only".
pub fn has_permission<I, S>(role: &str, explicit_grants: I, wanted: &str) -> bool
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    if !is_known_permission(wanted) {
        return false;
    }
    if role == "admin" {
        return true;
    }
    if role_default_permissions(role).contains(&wanted) {
        return true;
    }
    explicit_grants
        .into_iter()
        .any(|grant| grant.as_ref() == wanted)
}

#[cfg(test)]
mod tests {
    use super::*;

    const EMPTY: [&str; 0] = [];

    #[test]
    fn catalog_is_well_formed() {
        assert_eq!(
            MODERATION_PERMISSIONS.len(),
            11,
            "plan §6 lists exactly 11 moderation.* permissions"
        );
        for p in MODERATION_PERMISSIONS {
            assert!(
                p.starts_with("moderation."),
                "every catalog entry is namespaced under `moderation.`: {p}"
            );
        }
        let unique: BTreeSet<&&str> = MODERATION_PERMISSIONS.iter().collect();
        assert_eq!(
            unique.len(),
            MODERATION_PERMISSIONS.len(),
            "catalog must not contain duplicate permission strings"
        );
    }

    #[test]
    fn markers_match_catalog() {
        assert_eq!(ComplaintView::PERMISSION, "moderation.complaint.view");
        assert_eq!(CaseManage::PERMISSION, "moderation.case.manage");
        assert_eq!(ActionBanIp::PERMISSION, "moderation.action.ban_ip");
        assert_eq!(HistoryView::PERMISSION, "moderation.history.view");
        for p in [
            ComplaintView::PERMISSION,
            ComplaintResolve::PERMISSION,
            CaseView::PERMISSION,
            CaseManage::PERMISSION,
            ActionKick::PERMISSION,
            ActionMute::PERMISSION,
            ActionBan::PERMISSION,
            ActionBanIp::PERMISSION,
            NoteView::PERMISSION,
            NoteWrite::PERMISSION,
            HistoryView::PERMISSION,
        ] {
            assert!(is_known_permission(p), "marker {p} must be in the catalog");
        }
    }

    #[test]
    fn moderator_default_is_a_subset_of_the_catalog() {
        for p in MODERATOR_DEFAULT_PERMISSIONS {
            assert!(
                is_known_permission(p),
                "moderator default {p} must be a real catalog permission"
            );
        }
        let unique: BTreeSet<&&str> = MODERATOR_DEFAULT_PERMISSIONS.iter().collect();
        assert_eq!(
            unique.len(),
            MODERATOR_DEFAULT_PERMISSIONS.len(),
            "moderator default set must not contain duplicates"
        );
    }

    /// Security regression: the `moderator` role default is exactly the
    /// catalog minus `moderation.action.ban_ip`. If a future catalog entry
    /// is added without a deliberate decision, this fails — a new permission
    /// cannot silently fall into the role default.
    #[test]
    fn moderation_default_is_catalog_minus_ban_ip() {
        let expected: BTreeSet<&str> = MODERATION_PERMISSIONS
            .iter()
            .copied()
            .filter(|p| *p != "moderation.action.ban_ip")
            .collect();
        let actual: BTreeSet<&str> = MODERATOR_DEFAULT_PERMISSIONS.iter().copied().collect();
        assert_eq!(
            actual, expected,
            "moderator default must be the full catalog minus the ban_ip collateral-damage gate"
        );
    }

    /// The collateral-damage gate is the whole point of decision 5's
    /// fine-grained model: a default moderator must NOT be able to IP-ban.
    #[test]
    fn moderator_cannot_ip_ban_without_an_explicit_grant() {
        assert!(
            !has_permission("moderator", EMPTY, ActionBanIp::PERMISSION),
            "a default moderator must not hold the IP-ban gate"
        );
        assert!(
            !MODERATOR_DEFAULT_PERMISSIONS.contains(&"moderation.action.ban_ip"),
            "ban_ip must never appear in the role default set"
        );
    }

    #[test]
    fn moderator_ip_ban_passes_with_an_explicit_grant() {
        assert!(has_permission(
            "moderator",
            ["moderation.action.ban_ip"],
            ActionBanIp::PERMISSION
        ));
    }

    #[test]
    fn admin_holds_the_entire_catalog() {
        let eff = effective_permissions("admin", EMPTY);
        assert_eq!(eff.len(), MODERATION_PERMISSIONS.len());
        for p in MODERATION_PERMISSIONS {
            assert!(has_permission("admin", EMPTY, p));
        }
        assert!(has_permission("admin", EMPTY, ActionBanIp::PERMISSION));
    }

    #[test]
    fn admin_denies_a_non_catalog_permission() {
        assert!(!has_permission("admin", EMPTY, "moderation.bogus"));
        assert!(
            effective_permissions("admin", EMPTY)
                .iter()
                .all(|p| is_known_permission(p))
        );
    }

    #[test]
    fn moderator_default_resolution() {
        let eff = effective_permissions("moderator", EMPTY);
        let expected: BTreeSet<String> = MODERATOR_DEFAULT_PERMISSIONS
            .iter()
            .map(|p| (*p).to_string())
            .collect();
        assert_eq!(eff, expected);
        assert!(has_permission("moderator", EMPTY, ActionKick::PERMISSION));
        assert!(has_permission("moderator", EMPTY, CaseManage::PERMISSION));
    }

    #[test]
    fn moderator_explicit_grant_is_unioned_with_the_default() {
        let eff = effective_permissions("moderator", ["moderation.action.ban_ip"]);
        assert!(eff.contains("moderation.action.ban_ip"));
        assert!(eff.contains("moderation.action.kick"));
        assert_eq!(eff.len(), MODERATOR_DEFAULT_PERMISSIONS.len() + 1);
    }

    #[test]
    fn viewer_holds_nothing_by_default() {
        assert!(
            effective_permissions("viewer", EMPTY).is_empty(),
            "a viewer sees nothing moderation (plan §6)"
        );
        assert!(!has_permission("viewer", EMPTY, CaseView::PERMISSION));
    }

    #[test]
    fn viewer_with_an_explicit_grant_holds_only_that_grant() {
        let eff = effective_permissions("viewer", ["moderation.case.view"]);
        assert_eq!(eff.len(), 1);
        assert!(eff.contains("moderation.case.view"));
        assert!(has_permission(
            "viewer",
            ["moderation.case.view"],
            CaseView::PERMISSION
        ));
        assert!(!has_permission(
            "viewer",
            ["moderation.case.view"],
            CaseManage::PERMISSION
        ));
    }

    #[test]
    fn unknown_grant_strings_are_ignored() {
        let eff =
            effective_permissions("viewer", ["moderation.removed.legacy", "not-a-permission"]);
        assert!(
            eff.is_empty(),
            "unknown grant strings are dropped on resolution"
        );
        assert!(!has_permission(
            "viewer",
            ["moderation.removed.legacy"],
            "moderation.removed.legacy"
        ));
    }

    #[test]
    fn unknown_role_is_fail_closed() {
        assert!(effective_permissions("operator", EMPTY).is_empty());
        assert!(!has_permission("operator", EMPTY, CaseView::PERMISSION));
    }
}
